### ISSUE TITLE
Cannot Compile - LOT of errors

### ISSUE THREAD

**Issue by GFA-SkyRanger** [hasenradball/DS3231-RTC#7]
I used the default File "DS3231_set"

`In file included from /tmp/arduino_modified_sketch_199840/DS3231_set.ino:11:0:
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:68:19: error: field '_tm' has incomplete type
         struct tm _tm;
                   ^
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h: In member function 'int16_t DateTime::getYear() const':
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:42:44: error: '_tm' was not declared in this scope
         int16_t getYear()   const { return _tm.tm_year + 1900; }
                                            ^
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h: In member function 'int8_t DateTime::getMonth() const':
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:43:46: error: '_tm' was not declared in this scope
         int8_t getMonth()   const   { return _tm.tm_mon + 1; }
                                              ^
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h: In member function 'int8_t DateTime::getDay() const':
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:44:46: error: '_tm' was not declared in this scope
         int8_t getDay()     const   { return _tm.tm_mday; }
                                              ^
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h: In member function 'int8_t DateTime::getHour() const':
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:45:46: error: '_tm' was not declared in this scope
         int8_t getHour()    const   { return _tm.tm_hour; }
                                              ^
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h: In member function 'int8_t DateTime::getMinute() const':
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:46:46: error: '_tm' was not declared in this scope
         int8_t getMinute()  const   { return _tm.tm_min; }
                                              ^
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h: In member function 'int8_t DateTime::getSecond() const':
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:47:46: error: '_tm' was not declared in this scope
         int8_t getSecond()  const   { return _tm.tm_sec; }
                                              ^
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h: In member function 'int8_t DateTime::getWeekDay() const':
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:48:44: error: '_tm' was not declared in this scope
         int8_t getWeekDay() const { return _tm.tm_wday; }
                                            ^
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h: In member function 'int16_t DateTime::getYearDay() const':
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:49:45: error: '_tm' was not declared in this scope
         int16_t getYearDay() const { return _tm.tm_yday; }
                                             ^
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h: In member function 'int16_t DateTime::getDST() const':
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:50:46: error: '_tm' was not declared in this scope
         int16_t getDST()    const   { return _tm.tm_isdst; }
                                              ^
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h: At global scope:
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:74:29: error: 'TwoWire' has not been declared
         static DateTime now(TwoWire &_Wire = Wire);
                             ^
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:74:46: error: could not convert 'Wire' from 'USI_TWI' to 'int&'
         static DateTime now(TwoWire &_Wire = Wire);
                                              ^
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:82:24: error: expected ')' before '&' token
         DS3231(TwoWire &twowire);
                        ^
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:84:9: error: 'TwoWire' does not name a type
         TwoWire &_Wire;
         ^
In file included from /tmp/arduino_modified_sketch_199840/DS3231_set.ino:11:0:
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h: In member function 'byte DS3231::getRegisterValue()':
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:238:13: error: '_Wire' was not declared in this scope
             _Wire.requestFrom(CLOCK_ADDRESS, 1);
             ^
/tmp/arduino_modified_sketch_199840/DS3231_set.ino: In function 'void loop()':
DS3231_set:88:35: error: 'date' was not declared in this scope
         getDateStuff(year, month, date, dOW, hour, minute, second);
                                   ^
DS3231_set:88:41: error: 'dOW' was not declared in this scope
         getDateStuff(year, month, date, dOW, hour, minute, second);
                                         ^
DS3231_set:93:27: error: no matching function for call to 'DS3231::setYear(<unresolved overloaded function type>)'
         myRTC.setYear(year);
                           ^
/tmp/arduino_modified_sketch_199840/DS3231_set.ino:93:27: note: candidate is:
In file included from /tmp/arduino_modified_sketch_199840/DS3231_set.ino:11:0:
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:134:14: note: void DS3231::setYear(byte)
         void setYear(byte year);
              ^
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:134:14: note:   no known conversion for argument 1 from '<unresolved overloaded function type>' to 'byte {aka unsigned char}'
DS3231_set:94:29: error: no matching function for call to 'DS3231::setMonth(<unresolved overloaded function type>)'
         myRTC.setMonth(month);
                             ^
/tmp/arduino_modified_sketch_199840/DS3231_set.ino:94:29: note: candidate is:
In file included from /tmp/arduino_modified_sketch_199840/DS3231_set.ino:11:0:
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:132:14: note: void DS3231::setMonth(byte)
         void setMonth(byte month);
              ^
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:132:14: note:   no known conversion for argument 1 from '<unresolved overloaded function type>' to 'byte {aka unsigned char}'
DS3231_set:97:27: error: no matching function for call to 'DS3231::setHour(<unresolved overloaded function type>)'
         myRTC.setHour(hour);
                           ^
/tmp/arduino_modified_sketch_199840/DS3231_set.ino:97:27: note: candidate is:
In file included from /tmp/arduino_modified_sketch_199840/DS3231_set.ino:11:0:
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:126:14: note: void DS3231::setHour(byte)
         void setHour(byte hour);
              ^
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:126:14: note:   no known conversion for argument 1 from '<unresolved overloaded function type>' to 'byte {aka unsigned char}'
DS3231_set:98:31: error: no matching function for call to 'DS3231::setMinute(<unresolved overloaded function type>)'
         myRTC.setMinute(minute);
                               ^
/tmp/arduino_modified_sketch_199840/DS3231_set.ino:98:31: note: candidate is:
In file included from /tmp/arduino_modified_sketch_199840/DS3231_set.ino:11:0:
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:124:14: note: void DS3231::setMinute(byte)
         void setMinute(byte minute);
              ^
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:124:14: note:   no known conversion for argument 1 from '<unresolved overloaded function type>' to 'byte {aka unsigned char}'
DS3231_set:99:31: error: no matching function for call to 'DS3231::setSecond(<unresolved overloaded function type>)'
         myRTC.setSecond(second);
                               ^
/tmp/arduino_modified_sketch_199840/DS3231_set.ino:99:31: note: candidate is:
In file included from /tmp/arduino_modified_sketch_199840/DS3231_set.ino:11:0:
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:122:14: note: void DS3231::setSecond(byte)
         void setSecond(byte second);
              ^
/home/bastel/Arduino/libraries/DS3231-RTC/src/DS3231-RTC.h:122:14: note:   no known conversion for argument 1 from '<unresolved overloaded function type>' to 'byte {aka unsigned char}'
DS3231_set:104:43: error: invalid operands of types '<unresolved overloaded function type>' and 'int' to binary 'operator+'
         myRTC.setA1Time(dOW, hour, minute+1, second, 0x0, true,
                                           ^
DS3231_set:107:44: error: invalid operands of types '<unresolved overloaded function type>' and 'int' to binary 'operator+'
         myRTC.setA2Time(date, hour, minute+2, 0x0, false, false,
                                            ^
Bibliothek Wire im Ordner: /home/bastel/.arduino15/packages/digistump/hardware/avr/1.6.7/libraries/Wire (legacy) wird verwendet
Bibliothek DS3231-RTC in Version 1.0.0 im Ordner: /home/bastel/Arduino/libraries/DS3231-RTC  wird verwendet
Bibliothek Time_alt im Ordner: /home/bastel/Arduino/libraries/Time_alt (legacy) wird verwendet
exit status 1
'date' was not declared in this scope`

**Comment by hasenradball** [comment]
@GFA-SkyRanger
Hi, for sure, if I would send you such an unstructured text, and no explanation what you did exactely. Would you be able to understand what I did?
😊

Please provide a small sketch which causes this output.
Just with the error message it is hard to understand.

**Comment by hasenradball** [comment]
@GFA-SkyRanger
Hi, I checked the `example/DS3231_set.ino`.
on the following MCUs:
- Nano 33 IOT
- Nano
- ESP8266

I can compile with no Errors.
Please provide more infos.

Thanks

**Comment by GFA-SkyRanger** [comment]
I solved the problem.

In general, everyone who programs the DS3231 library (i tested all of them, available in the library-manager) consistently ignores capitalization. 
Have you ever heard of Linux and the case sensitivity of files, right?
Every time I have to change "timer.h" to "Timer.h" in the DS3231.h.
But that's exactly where the problem lies, because THAT seems to be defective.
I have now found the original DS3231 with version 1.0.2 from an old backup, so I can program my Digispark Mini USB perfectly.
He doesn't use the timer library.

What do we learn from this? Never touch a running system!
I won't do any more lib updates because then some garbage will be added and nothing will work afterwards.

A few years ago I made a small USB clock with DS3231, an OLED display and the Digispark Mini USB. I had to reset the time because the battery was empty.
Of course I updated all the libs.
Bad mistake.

Nevertheless, thank you for your efforts. I'm leaving all the libs exactly as they are now.
Then I can at least continue to maintain my other projects, which would have become almost unusable thanks to Lib Updates.

**Comment by GFA-SkyRanger** [comment]
> @GFA-SkyRanger Hi, for sure, if I would send you such an unstructured text, and no explanation what you did exactely. Would you be able to understand what I did? 😊
> 
> Please provide a small sketch which causes this output. Just with the error message it is hard to understand.

Not my fault, i had a really nice formatted text. Git makes this text corrupt. Didnt knew that.

**Comment by hasenradball** [comment]
@GFA-SkyRanger Have a really good morning! :-)

I think I got the issue, but not 100% sure.
Let me give a short explanation, please. :-)

> Have you ever heard of Linux and the case sensitivity of files, right?
Every time I have to change "timer.h" to "Timer.h" in the DS3231.h.
But that's exactly where the problem lies, because THAT seems to be defective.

1) each cpp compiler uses case sensitivity for `#include`!
2) I neither use `Timer.h` nor `timer.h` in this Library!
 I also not in examples 

==> I use in this library `time.h` !!!
This has an specific benefit:

- `time.h` use the cpp time library of the microcontroller core which makes the usage of  `struct_tm` possible.
`struct_tm` hold all time relevant values for you, see [cpp reference](https://cplusplus.com/reference/ctime/tm/)

Which additionally allows time formatted printing in one line, like:

`strf_DateTime(char *buffer, size_t buffersize, const char *formatSpec)`
```
Example: 
// Use smart print function from DateTime class
    Serial.print("\nUse strf_DateTime function:\n ");
    // provide a buffer
    char buffer[80];
    datetime.strf_DateTime(buffer, sizeof(buffer));
    Serial.println(buffer);
```
This uses the official cpp strftime functionality [cpp strftime](https://cplusplus.com/reference/ctime/strftime/)

So I hope I could give a small explanation.
And I hope you give this library a second try, because it is better maintained than others.

PS: Send me your sketch I wil make it work for you with this library.
:-)

**Comment by GFA-SkyRanger** [comment]
>     2. I neither use `Timer.h` nor `timer.h` in this Library!
>        I also not in examples
> 
> 
> ==> I use in this library `time.h` !!! This has an specific benefit:
> 

Ok, my mistake, of course I meant time.h.


The Time.h is faulty, it doesn't work with the Digispark Mini USB.

In the original DS3231.h, the time.h is not used in version 1.0.2 and so this version works.

And using Time.h might work for other microcontrollers like the Nano or the STM32, but not for the Digispark.
The fact is that it is apparently faulty or not compatible.


> PS: Send me your sketch I wil make it work for you with this library. :-)

It's your own sketch.
"examples/DS3231_set/DS3231_set.ino"

I just wanted to set the date and time.
I just filled the variables with the appropriate data.
The sketch is not flawed. 
But the Time library.

I used the sketch to set the time after using the old original library.

Here i compiled your original fresh installed Library for Arduino NANO:
![DS3231-RTC für NANO](https://github.com/hasenradball/DS3231-RTC/assets/23200174/e2e6878c-b8a1-49c5-b71c-01cc467fa197)
It compiled perfect. Doesn't use time.h it seems so, don't know why, but no error.

Here it is the output as i would compile it for the Digispark. It seems, that it trys to use time.h (You can see it by urself in the screenshot) but can't find the file, because of typo.
![DS3231-RTC für Digispark](https://github.com/hasenradball/DS3231-RTC/assets/23200174/8119adf8-1dfc-4aec-bfe8-e767fd322560)


Then i fixed your error, and put an capital T instead of an small t:
![DS3231-RTC h geändert](https://github.com/hasenradball/DS3231-RTC/assets/23200174/da3aa769-77bd-490e-b49a-790449b7a6ee)

Now it trys to compile, but Time.h not compatible. May be not your fault but, you can see.
![DS3231-RTC für Digispark mit korrigierter DS3231-RTC h](https://github.com/hasenradball/DS3231-RTC/assets/23200174/b07ca1a1-b4f2-4759-8c2d-0038dfa4d73f)


Two things, first, with the NANO it compiles. no error because of capital T or not.
second, for digispark it seems to try to use time.h AND if i fix the error, the Time.h seems not to work.

Because of corrupting the text from Git, here a screenshot of the errors while trying to compile.:
![Compilierungsfehler Digispark](https://github.com/hasenradball/DS3231-RTC/assets/23200174/4045302c-d37f-4b85-9f7d-f805e9fd5f52)

I have the same thing on two different PCs.
One with Linux Mint Mate 20.3 with an i9-7980XE and 128 GB RAM, and the other PC mit Linux Mint Mate 21.2 with an Intel J4205 and 8 GB RAM.
Main PC is for writing Sketches and the other is for compiling und Programming the Microcontrollers.


In my opinion, the whole discussion is pointless anyway, because on the one hand the error in the DS3231-RTC.h has still not been corrected, although I have already noted that you have to pay attention to the upper and lower case and on the other hand I have it Error already solved even with the old libraries.

Because there are many libraries for the same purpose and you don't really know which one to use, I'm not tied to any library. So in principle I don't care which library I use effectively or not.

The fact is, they are all flawed because no one cares about the capitalization and ultimately it just has to work.
I don't care whether I complain or not and to whom.

The whole thing only got rolling because I wanted to send an error report out of panic and short-circuited action in order to get help if necessary because I didn't know where to start looking for errors. Then all that mattered to me was that it had worked. So look for a backup, restore everything the way it was back then, DO NOT carry out any updates and everything worked as expected.

Looking back, I'm sorry that I opened such a barrel over nothing.

Nobody seems to be interested in reporting errors anyway, because if EVERYONE has the same error and no one fixes it, then I shouldn't care. I fix the error locally and it's fine.

Besides, with the faulty "Time" library I'm out of place here anyway. It's not your fault if they build incompatible libraries.


I wish you all the best and thank you for your efforts and apologize again for my short-circuit action of creating a bug report for a mistake you did not make.

**Comment by hasenradball** [comment]
@GFA-SkyRanger 

I can give you an hint from my expirience.

a) try not to use the "Time.h" from the Arduino IDE.

> Here i compiled your original fresh installed Library for Arduino NANO:

b) Sure also the Nano uses the time.h, but its own in the AVR-CORE included time functions.
see [AVR time](https://www.nongnu.org/avr-libc/user-manual/group__avr__time.html)
Also the ESP8266, ESP32 have it MCU specific time implementations (behind the scenes).

c) If you want to set your DS3231 I use always an esp8266.
 - it connects to the WLAN
 - gets the time from timeserver
 - write to DS3231
 - finish
 -:)
Maybee I should make a new example for this.
And you don't need any "Time.h" anymore :-)

PS:
here you see the time src file location from the ESP8266.
[time.cpp](https://github.com/esp8266/Arduino/blob/master/cores/esp8266/time.cpp)
